# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fA1mZQnoGgYzpUmr9ZSU-4bvdCyJoBPF
"""

import requests
import pandas as pd
import urllib.parse as urlp
from statsmodels.tsa.statespace.sarimax import SARIMAX
from requests_futures.sessions import FuturesSession
import concurrent.futures

# ---------------- Funciones de descarga y parseo ----------------

def build_full_url(start_date, end_date, latitude, longitude, variable):
    """Construye la URL completa para una petición específica a la API de NASA GES DISC."""
    base_url = "https://hydro1.gesdisc.eosdis.nasa.gov/daac-bin/access/timeseries.cgi"
    query_parameters = {
        "variable": variable,
        "type": "asc2",
        "location": f"GEOM:POINT({longitude}, {latitude})",
        "startDate": start_date,
        "endDate": end_date,
    }
    # Codificar los parámetros de la URL
    return base_url + "?" + "&".join([f"{k}={urlp.quote(query_parameters[k])}" for k in query_parameters])

def parse_time_series(ts_str):
    """Parsea el string de la serie temporal en un DataFrame de Pandas."""
    # Usamos StringIO para tratar el string como un archivo en memoria
    df = pd.read_table(pd.io.common.StringIO(ts_str), sep="\t", names=["time","data"], header=10, parse_dates=["time"])
    df = df.dropna(subset=['time','data'])
    return df

# ---------------- Parámetros ----------------
MONTERREY_LAT = 25.68
MONTERREY_LON = -100.31

VARIABLES = {
    "Tair": "NLDAS2:NLDAS_FORA0125_H_v2.0:Tair",
    "Rainf": "NLDAS2:NLDAS_FORA0125_H_v2.0:Rainf"
}

# Rangos históricos de 6 meses aproximados (mayo a octubre de 2025)
fechas_rangos = [
    ("2025-05-01T00", "2025-06-01T00"),
    ("2025-06-01T00", "2025-07-01T00"),
    ("2025-07-01T00", "2025-08-01T00"),
    ("2025-08-01T00", "2025-09-01T00"),
    ("2025-09-01T00", "2025-10-01T00"),
]

# ---------------- Función de predicción OPTIMIZADA ----------------
def predecir_clima_fecha_futura(fechas_rangos, fecha_objetivo_str, lat, lon):

    # 1. Preparar y lanzar todas las peticiones concurrentemente
    # Usamos un ThreadPoolExecutor para concurrencia (velocidad en I/O)
    session = FuturesSession(executor=concurrent.futures.ThreadPoolExecutor(max_workers=10))
    all_futures = {}

    print("Iniciando descarga concurrente de datos históricos (10 peticiones)...")
    for start, end in fechas_rangos:
        # Tair
        url_tair = build_full_url(start, end, lat, lon, VARIABLES['Tair'])
        all_futures[(start, 'Tair')] = session.get(url_tair)

        # Rainf
        url_rain = build_full_url(start, end, lat, lon, VARIABLES['Rainf'])
        all_futures[(start, 'Rainf')] = session.get(url_rain)

    # 2. Consolidar datos históricos
    all_dfs = []

    # Recorrer los resultados de las peticiones a medida que se completan
    for (start, var_name), future in all_futures.items():
        try:
            r = future.result(timeout=10)
            if r.status_code == 200:
                df = parse_time_series(r.text)
                # Renombrar y establecer el índice de tiempo
                df = df.rename(columns={'data': var_name}).set_index('time')
                all_dfs.append(df)
            else:
                print(f"Advertencia: Error {r.status_code} para {var_name} en {start}. URL: {r.url}")
        except Exception as e:
            print(f"Error grave al obtener datos para {var_name} en {start}: {e}")

    if not all_dfs:
        print("No se pudieron obtener datos. Terminando.")
        return

    # Unir y consolidar todos los DataFrames
    df_temp_combined = pd.concat(all_dfs).sort_index()

    # Pivotear las variables (Tair y Rainf) a columnas separadas
    # Esto resuelve el problema del KeyError anterior
    df_total = df_temp_combined.groupby(df_temp_combined.index).first().unstack(level=1).dropna()

    # Preparar serie diaria
    # Reesampling: Obtener la media diaria de Tair y Rainf
    ts_temp = df_total['Tair'].resample('D').mean().interpolate()
    ts_rain = df_total['Rainf'].resample('D').mean().interpolate()

    # Fecha futura y cálculo de días a predecir
    fecha_objetivo = pd.to_datetime(fecha_objetivo_str)
    dias_a_predecir = (fecha_objetivo - ts_temp.index[-1]).days
    if dias_a_predecir <= 0:
        print("La fecha objetivo debe ser posterior al último dato histórico.")
        return

    # 3. Modelo SARIMA para Tair (Optimizado para velocidad)
    print(f"Ajustando modelo SARIMAX ({len(ts_temp)} días de datos). Esto tomará un momento...")
    # Se usa seasonal_order=(1,1,1,7) para estacionalidad semanal, que es más rápida que s=30.
    model = SARIMAX(ts_temp, order=(1,1,1), seasonal_order=(1,1,1,7),
                    enforce_stationarity=False, enforce_invertibility=False)

    # Usamos 'lbfgs' para un ajuste más rápido del modelo.
    model_fit = model.fit(disp=False, method='lbfgs')

    # Realizar la predicción
    forecast = model_fit.get_forecast(steps=dias_a_predecir)
    pred_temp = forecast.predicted_mean.iloc[-1]

    # Probabilidad de lluvia basada en histórico (rápida)
    rain_binary = (ts_rain > 0).astype(int)
    prob_lluvia = rain_binary.mean()

    # Mostrar resultados
    print(f"\n--- Predicción para {fecha_objetivo.date()} ---")
    print(f"Temperatura (Tair): {pred_temp:.2f} K")
    print(f"Probabilidad aproximada de lluvia: {prob_lluvia*100:.1f}%")

# ---------------- Uso de la función ----------------
fecha_futura = "2025-10-06"
predecir_clima_fecha_futura(fechas_rangos, fecha_futura, MONTERREY_LAT, MONTERREY_LON)