# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1am--PIuWuMNZEHWaTFD0PajB7ozrwrhX
"""

import requests
import pandas as pd
import urllib.parse as urlp
from statsmodels.tsa.statespace.sarimax import SARIMAX

# ---------------- Funciones de descarga y parseo ----------------
def get_time_series(start_date, end_date, latitude, longitude, variable):
    base_url = "https://hydro1.gesdisc.eosdis.nasa.gov/daac-bin/access/timeseries.cgi"
    query_parameters = {
        "variable": variable,
        "type": "asc2",
        "location": f"GEOM:POINT({longitude}, {latitude})",
        "startDate": start_date,
        "endDate": end_date,
    }
    full_url = base_url + "?" + "&".join([f"{k}={urlp.quote(query_parameters[k])}" for k in query_parameters])
    iteration = 0
    done = False
    while not done and iteration < 5:
        r = requests.get(full_url)
        if r.status_code == 200:
            done = True
        else:
            import time
            time.sleep(1)
            iteration += 1
    if not done:
        raise Exception(f"Error código {r.status_code} en la URL {full_url}")
    return r.text

def parse_time_series(ts_str):
    df = pd.read_table(pd.io.common.StringIO(ts_str), sep="\t", names=["time","data"], header=10, parse_dates=["time"])
    df = df.dropna(subset=['time','data'])
    return df

# ---------------- Parámetros ----------------
MONTERREY_LAT = 25.68
MONTERREY_LON = -100.31

VARIABLES = {
    "Tair": "NLDAS2:NLDAS_FORA0125_H_v2.0:Tair",
    "Rainf": "NLDAS2:NLDAS_FORA0125_H_v2.0:Rainf"
}

# ---------------- Rangos históricos de 6 meses aproximados ----------------
fechas_rangos = [
    ("2025-05-01T00", "2025-06-01T00"),
    ("2025-06-01T00", "2025-07-01T00"),
    ("2025-07-01T00", "2025-08-01T00"),
    ("2025-08-01T00", "2025-09-01T00"),
    ("2025-09-01T00", "2025-10-01T00"),
]

# ---------------- Función de predicción ----------------
def predecir_clima_fecha_futura(fechas_rangos, fecha_objetivo_str, lat, lon):
    # Consolidar datos históricos
    df_total = pd.DataFrame()
    for start, end in fechas_rangos:
        # Tair
        raw_tair = get_time_series(start, end, lat, lon, VARIABLES['Tair'])
        df_tair = parse_time_series(raw_tair).rename(columns={'data':'Tair'})

        # Rainf
        raw_rain = get_time_series(start, end, lat, lon, VARIABLES['Rainf'])
        df_rain = parse_time_series(raw_rain).rename(columns={'data':'Rainf'})

        # Merge Tair y Rainf por tiempo
        df_temp = pd.merge(df_tair, df_rain, on='time', how='inner')
        df_total = pd.concat([df_total, df_temp], ignore_index=True)

    # Preparar serie diaria
    df_total = df_total.set_index('time').sort_index()
    ts_temp = df_total['Tair'].resample('D').mean().interpolate()
    ts_rain = df_total['Rainf'].resample('D').mean().interpolate()

    # Fecha futura
    fecha_objetivo = pd.to_datetime(fecha_objetivo_str)
    dias_a_predecir = (fecha_objetivo - ts_temp.index[-1]).days
    if dias_a_predecir <= 0:
        print("La fecha objetivo debe ser posterior al último dato histórico.")
        return

    # Modelo SARIMA para Tair
    model = SARIMAX(ts_temp, order=(1,1,1), seasonal_order=(1,1,1,30),
                    enforce_stationarity=False, enforce_invertibility=False)
    model_fit = model.fit(disp=False)
    forecast = model_fit.get_forecast(steps=dias_a_predecir)
    pred_temp = forecast.predicted_mean[-1]

    # Probabilidad de lluvia basada en histórico
    rain_binary = (ts_rain > 0).astype(int)
    prob_lluvia = rain_binary.mean()  # probabilidad global aproximada

    # Mostrar resultados solo para la fecha futura
    print(f"\n--- Predicción para {fecha_objetivo.date()} ---")
    print(f"Temperatura (Tair): {pred_temp:.2f} K")
    print(f"Probabilidad aproximada de lluvia: {prob_lluvia*100:.1f}%")

# ---------------- Uso de la función ----------------
fecha_futura = "2025-10-06"
predecir_clima_fecha_futura(fechas_rangos, fecha_futura, MONTERREY_LAT, MONTERREY_LON)