# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fA1mZQnoGgYzpUmr9ZSU-4bvdCyJoBPF
"""

import requests
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme(style="darkgrid")
import urllib
import urllib.parse as urlp
import io
import warnings
warnings.filterwarnings("ignore")

# Para mostrar gráficos en entornos interactivos (como Jupyter)
# %matplotlib inline

# --- Definición de funciones (mantener igual) ---

def get_time_series(start_date,end_date,latitude,longitude,variable):
    """
    Llama al servicio de 'data rods' para obtener una serie de tiempo.
    """
    base_url = "https://hydro1.gesdisc.eosdis.nasa.gov/daac-bin/access/timeseries.cgi"
    query_parameters = {
        "variable": variable,
        "type": "asc2",
        "location": f"GEOM:POINT({longitude}, {latitude})",
        "startDate": start_date,
        "endDate": end_date,
    }
    full_url = base_url+"?"+ \
         "&".join(["{}={}".format(key,urlp.quote(query_parameters[key])) for key in query_parameters])
    print(f"URL de Solicitud ({variable.split(':')[-1]}): {full_url}")
    iteration = 0
    done = False
    while not done and iteration < 5:
        r=requests.get(full_url)
        if r.status_code == 200:
            done = True
        else:
            # Si hay un error, esperamos un momento antes de reintentar
            import time
            time.sleep(1)
            iteration +=1

    if not done:
        # Aquí es donde se lanza la excepción si falla después de 5 intentos
        raise Exception(f"Error código {r.status_code} de la url {full_url} : {r.text}")

    return r.text

def parse_time_series(ts_str):
    """
    Analiza la respuesta de 'data rods' y la convierte en un DataFrame.
    """
    lines = ts_str.split("\n")
    parameters = {}
    for line in lines[2:11]:
        try:
            key,value = [s.strip() for s in line.split("=")]
            parameters[key] = value
        except:
            continue

    df = pd.read_table(io.StringIO(ts_str),sep="\t",
                      names=["time","data"],
                      header=10,parse_dates=["time"])

    df = df.dropna(subset=['time', 'data'])

    return parameters, df

# --- Parámetros para Monterrey y el período de 5 días ---

MONTERREY_LAT = 25.68
MONTERREY_LON = -100.31
# Rango de 5 días (Del 15/09/2025 hasta la medianoche del 20/09/2025)
START_DATE = "2025-09-15T00"
END_DATE = "2025-09-20T00" # Excluye el día 20. Si quieres incluir el día 20, debes poner '2025-09-21T00'

# El identificador del producto fue corregido a 'NLDAS_FORA0125_H_v2.0'
VARIABLES = {
    "Tair": "NLDAS2:NLDAS_FORA0125_H_v2.0:Tair",
    "Qair": "NLDAS2:NLDAS_FORA0125_H_v2.0:Qair",
    "Wind_E": "NLDAS2:NLDAS_FORA0125_H_v2.0:Wind_E",
    "Wind_N": "NLDAS2:NLDAS_FORA0125_H_v2.0:Wind_N",
    "PSurf": "NLDAS2:NLDAS_FORA0125_H_v2.0:PSurf",
    "Rainf": "NLDAS2:NLDAS_FORA0125_H_v2.0:Rainf",
    "LWdown": "NLDAS2:NLDAS_FORA0125_H_v2.0:LWdown",
}

# DataFrame para consolidar todos los datos
df_clima_completo = None
print(f"--- Obteniendo Datos Climáticos para Monterrey ({START_DATE.split('T')[0]} a {END_DATE.split('T')[0]}) ---")

for var_name, var_id in VARIABLES.items():
    print(f"Solicitando {var_name}...")

    # 1. Obtener la serie de tiempo
    raw_ts = get_time_series(
        start_date=START_DATE,
        end_date=END_DATE,
        latitude=MONTERREY_LAT,
        longitude=MONTERREY_LON,
        variable=var_id
    )

    # 2. Parsear el resultado
    parameters, df_data = parse_time_series(raw_ts)

    # 3. Renombrar la columna 'data' con el nombre de la variable
    df_data = df_data.rename(columns={'data': var_name})

    # 4. Consolidar el DataFrame
    if df_clima_completo is None:
        df_clima_completo = df_data
    else:
        # Unir las siguientes variables por la columna 'time' (fecha/hora)
        df_clima_completo = pd.merge(df_clima_completo, df_data, on='time', how='inner')

# ----------------------------------------------------------------------------------
# --- NUEVA LÓGICA DE EXTRACCIÓN Y VISUALIZACIÓN POR RANGO DE DÍAS ---
# ----------------------------------------------------------------------------------

df_clima_completo = df_clima_completo.set_index('time')

# Calcular el número de días en el rango solicitado
start_dt = pd.to_datetime(START_DATE.split('T')[0])
end_dt = pd.to_datetime(END_DATE.split('T')[0])
# Contamos los días. Si es '20' - '15', son 5 días completos (00:00 del 15 hasta 00:00 del 20)
num_dias = (end_dt - start_dt).days

if num_dias <= 1:
    # Caso 1: Rango de 1 día o menos. Mostrar todas las observaciones horarias.
    df_resultado = df_clima_completo.reset_index()
    print("\n--- ¡Rango de un día! Mostrando todas las observaciones horarias ---")
    titulo = f"Datos Horarios para el {start_dt.strftime('%d-%b-%Y')}"

else:
    # Caso 2: Rango de múltiples días. Mostrar solo una observación por día.

    # 1. Filtramos la hora que quieres usar como representativa (ejemplo: 12:00:00 PM)
    # Se utiliza `.between_time` para seleccionar la hora deseada en el rango de cada día.
    df_muestra_diaria = df_clima_completo.between_time('12:00', '12:00')

    # Si no se encuentra la hora exacta (por decimales de tiempo en la API),
    # se podría usar .resample('D').mean() para obtener la media diaria,
    # pero para obtener UN solo punto como pediste, el filtro de tiempo es mejor.

    df_resultado = df_muestra_diaria.reset_index()
    print(f"\n--- ¡Rango de {num_dias} días! Mostrando una observación diaria (12:00:00 PM) ---")
    titulo = f"Muestra Diaria (12 PM) del {start_dt.strftime('%d-%b-%Y')} al {end_dt.strftime('%d-%b-%Y')}"


# --- RESULTADO FINAL Y GRÁFICOS ---

print(titulo)
print("-" * len(titulo))
print(df_resultado)


# Gráfico para la Temperatura del Aire (Tair)
plt.figure(figsize=(15, 6))
sns.lineplot(data=df_resultado, x="time", y="Tair", marker='o', color='red')
plt.title(f'Temperatura del Aire (Tair) en Monterrey - {titulo}', fontsize=14)
plt.ylabel('Tair (Kelvin)')
plt.xlabel('Fecha')
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

# Extracción de los datos de Presión Superficial
datos_presion_superficial = df_resultado['PSurf']
print("\n--- Primeros datos de Presión Superficial (PSurf) del resultado final ---")
print(datos_presion_superficial.head(num_dias if num_dias > 1 else 10))